version: '3.9'
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mynetwork2
    volumes:
      - ./DB/data:/var/opt/mssql/data
    healthcheck:
      test: ["CMD-SHELL", "opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: ./PRODUCTSAPI
    ports:
      - "80:8080"
    links:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork2
    depends_on:
      sqlserver:
        condition: service_healthy
networks:
  mynetwork2:
volumes:
  sqlserver-data:
