version: '3.9'
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  web:
    build: ./PRODUCTSAPI
    ports:
      - "80:8080"
    links:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    